FROM ubuntu:latest

RUN apt update
RUN apt install python3 -y
RUN apt-get -y install python3-pip
RUN pip3 install requests
RUN pip3 install pandas
RUN pip3 install numpy
RUN pip3 install scikit-learn
RUN pip3 install scipy
RUN pip3 install tensorflow
RUN pip3 install flask

WORKDIR /usr/app/src

COPY script.py ./

ENV PORT=8000

EXPOSE 8000

CMD ["python3", "./script.py"]