FROM ubuntu:latest

RUN apt update
RUN apt install python3 -y
RUN apt-get -y install python3-pip
RUN pip3 install flask
RUN pip3 install pandas
RUN pip3 install numpy
RUN pip3 install scikit-learn
RUN pip3 install scipy
RUN pip3 install tensorflow

WORKDIR /usr/app/src

COPY script.py ./

ENV PORT=8000

EXPOSE 8000

CMD ["python3", "script.py", "0.0.0.0:8000"]